# Generated by Django 3.1.5 on 2022-07-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explodindoMentes', '0002_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='explodindoMentes.position')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector', to='explodindoMentes.sector')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.ManyToManyField(blank=True, related_name='offices', to='explodindoMentes.Office'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='positions', to='explodindoMentes.Position'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='explodindoMentes.Sector'),
        ),
    ]
