# Generated by Django 3.1.5 on 2022-08-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explodindoMentes', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(default=''),
        ),
    ]
