# Generated by Django 3.1.5 on 2022-08-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explodindoMentes', '0007_auto_20220801_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
